# -----------------------------------------------------------------------------
# model
# -----------------------------------------------------------------------------
model:
    loss:
        CrossEntropyLoss:
            weight: [1.0, 1.0]

# -----------------------------------------------------------------------------
# dataset
# -----------------------------------------------------------------------------
dataset:
    type: 'YantaiDataset'
    data_root: '/opt/data/public02/manuag/zhangshuai/data'
    dataset: "yantai-12_v2345_unq_1008" # 12_v234_all_1c  12_v234_unq_1c
    classes: ['background', '1diaojiao', '2liewen', '3kongdong']
    #INDEX: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    labels: [0, 1, 2, 3, 3, 0, 0, 2, 0, 1]

#    mean: [123.675, 116.28, 103.53]
#    std: [58.395, 57.12, 57.375]
    to_rgb: True

    size: [512, 1024]
    crop_size: [512, 1024]

    samples_per_gpu: 4
    workers_per_gpu: 1


# -----------------------------------------------------------------------------
# runtime
# -----------------------------------------------------------------------------
runtime:
    seed: 4
    deterministic: None
    cudnn_benchmark: False
    gpu_ids: [0]
#    load_from: '/root/ManuVision-pytorch-encoding/encoding/data/ainno-yantai'
    work_dir: '../work_dir/manuvision/'


# -----------------------------------------------------------------------------
# schedule
# -----------------------------------------------------------------------------
schedule:
    optimizer:
        type: 'adamax'
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0005

    paramwise_cfg:
        lr_mult: 0.1
        decay_mult: 0.9

    lr_config:
        policy: 'cos'
        power: 0.9
        min_lr: 1e-4
        by_epoch: True
        warmup: 'linear'
        warmup_iters: 600
        warmup_ratio: 0.1
        warmup_by_epoch: False

    runner:
        type: 'EpochBasedRunner'
        max_epochs: 800

    checkpoint_config:
        by_epoch: True
        interval: 1

    evaluation:
        interval: 1
        metric: 'mIoU'
